location       = "Central Us"
rgname         = "devrg"
nsg1name       = "devnsg"
vnet1name      = "dev-vnet"
cidr           = "10.0.0.0/16"
interface_name = "Dev-interface"
nsgrule1name   = "dev-nsg-rule1"
devpip-name    = "Dev-Pip1"
